env:
  es2021: true
  node: true
  jest: true
plugins:
  - jest
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - Error
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
